#include <array>
#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <iostream>
#include <thread>

#include <dds/dds.h>

#include <SenseGlove/Core/HandLayer.hpp>
#include <SenseGlove/Core/HandPose.hpp>
#include <SenseGlove/Core/Library.hpp>
#include <SenseGlove/Core/SenseCom.hpp>
#include <SenseGlove/Core/Vect3D.hpp>

// Generated by: idlc -l c idl/glove_hand_msgs.idl
#include "glove_hand_msgs.h"

using namespace SGCore;
using namespace SGCore::Kinematics;

static std::atomic<bool> g_stop{false};
static constexpr std::chrono::milliseconds kPublishInterval{15}; // ~66.7 Hz

enum JointCode : uint8_t
{
    CMC = 0,
    MCP = 1,
    PIP = 2,
    DIP = 3,
    IP = 4,
    UNKNOWN = 255,
};

static void SignalHandler(int)
{
    g_stop = true;
}

static uint8_t ToJointCode(size_t fingerIndex, size_t jointIndex)
{
    if (fingerIndex == 0)
    {
        // Thumb: CMC -> MCP -> IP
        static const std::array<uint8_t, 3> thumbMap = {CMC, MCP, IP};
        return (jointIndex < thumbMap.size()) ? thumbMap[jointIndex] : UNKNOWN;
    }

    // Other fingers: MCP -> PIP -> DIP
    static const std::array<uint8_t, 3> fingerMap = {MCP, PIP, DIP};
    return (jointIndex < fingerMap.size()) ? fingerMap[jointIndex] : UNKNOWN;
}

static bool EnsureSenseCom()
{
    if (SenseCom::ScanningActive())
    {
        return true;
    }
    std::cout << "SenseCom not active, trying to start..." << std::endl;
    return SenseCom::StartupSenseCom();
}

static void FillHandEulerMessage(const HandPose &pose, glove_hand_msgs_msg_HandEuler &outMsg)
{
    const auto now = std::chrono::system_clock::now().time_since_epoch();
    const auto sec = std::chrono::duration_cast<std::chrono::seconds>(now);
    const auto nsec = std::chrono::duration_cast<std::chrono::nanoseconds>(now - sec);

    outMsg.stamp_sec = static_cast<int64_t>(sec.count());
    outMsg.stamp_nanosec = static_cast<uint32_t>(nsec.count());
    outMsg.is_right_hand = pose.IsRight();
    outMsg.valid_joint_count = 0;

    const auto &angles = pose.GetHandAngles(); // [finger][joint] -> Euler(roll,pitch,yaw)

    size_t outIndex = 0;
    for (size_t fingerIndex = 0; fingerIndex < angles.size() && outIndex < 15; ++fingerIndex)
    {
        for (size_t jointIndex = 0; jointIndex < angles[fingerIndex].size() && outIndex < 15; ++jointIndex)
        {
            const Vect3D &e = angles[fingerIndex][jointIndex];
            auto &j = outMsg.joints[outIndex];
            j.finger = static_cast<uint8_t>(fingerIndex);
            j.joint_index = static_cast<uint8_t>(jointIndex);
            j.joint = ToJointCode(fingerIndex, jointIndex);
            j.roll = e.GetX();
            j.pitch = e.GetY();
            j.yaw = e.GetZ();
            ++outIndex;
        }
    }

    outMsg.valid_joint_count = static_cast<uint8_t>(outIndex);
}

int main()
{
    signal(SIGINT, SignalHandler);
    signal(SIGTERM, SignalHandler);

    std::cout << "SGCore version: " << Library::Version() << std::endl;
    if (!EnsureSenseCom())
    {
        std::cerr << "Failed to start SenseCom." << std::endl;
        return 1;
    }

    dds_entity_t participant = dds_create_participant(DDS_DOMAIN_DEFAULT, nullptr, nullptr);
    if (participant < 0)
    {
        std::cerr << "dds_create_participant failed: " << dds_strretcode(-participant) << std::endl;
        return 1;
    }

    dds_entity_t topic = dds_create_topic(
        participant, &glove_hand_msgs_msg_HandEuler_desc, "/glove/hand_euler", nullptr, nullptr);
    if (topic < 0)
    {
        std::cerr << "dds_create_topic failed: " << dds_strretcode(-topic) << std::endl;
        dds_delete(participant);
        return 1;
    }

    dds_entity_t writer = dds_create_writer(participant, topic, nullptr, nullptr);
    if (writer < 0)
    {
        std::cerr << "dds_create_writer failed: " << dds_strretcode(-writer) << std::endl;
        dds_delete(participant);
        return 1;
    }

    while (!g_stop.load())
    {
        for (bool rightHand : {true, false})
        {
            if (!HandLayer::DeviceConnected(rightHand))
            {
                continue;
            }

            HandPose pose;
            if (!HandLayer::GetHandPose(rightHand, pose))
            {
                continue;
            }

            glove_hand_msgs_msg_HandEuler msg{};
            FillHandEulerMessage(pose, msg);

            dds_return_t rc = dds_write(writer, &msg);
            if (rc != DDS_RETCODE_OK)
            {
                std::cerr << "dds_write failed: " << dds_strretcode(-rc) << std::endl;
            }
        }

        std::this_thread::sleep_for(kPublishInterval);
    }

    dds_delete(participant);
    return 0;
}
