#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <csignal>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <memory>
#include <sstream>
#include <thread>

#include <dds/dds.h>

#include <SenseGlove/Core/HandLayer.hpp>
#include <SenseGlove/Core/HandPose.hpp>
#include <SenseGlove/Core/SenseCom.hpp>
#include <SenseGlove/Core/Vect3D.hpp>

// Generated by: idlc -l c idl/glove_hand_msgs.idl
#include "glove_hand_msgs.h"

using namespace SGCore;
using namespace SGCore::Kinematics;

static std::atomic<bool> g_stop{false};
static constexpr std::chrono::milliseconds kPublishInterval{15}; // ~66.7 Hz

static const std::array<const char *, 5> kFingerNames = {
    "Thumb", "Index", "Middle", "Ring", "Pinky"};

static void SignalHandler(int)
{
    g_stop = true;
}

static float QuantizeTo3Decimals(float value)
{
    return std::round(value * 1000.0f) / 1000.0f;
}

static bool EnsureSenseCom()
{
    if (SenseCom::ScanningActive())
    {
        return true;
    }
    std::cout << "SenseCom not active, trying to start..." << std::endl;
    return SenseCom::StartupSenseCom();
}

static std::string BuildCompactEulerText(const HandPose &pose)
{
    static const std::array<const char *, 3> kThumbJoints = {"CMC", "MCP", "IP"};
    static const std::array<const char *, 3> kFingerJoints = {"MCP", "PIP", "DIP"};
    const auto &angles = pose.GetHandAngles();

    std::ostringstream out;
    out << std::fixed << std::setprecision(3);
    for (size_t fingerIndex = 0; fingerIndex < kFingerNames.size(); ++fingerIndex)
    {
        if (fingerIndex > 0)
        {
            out << '\n';
        }
        out << kFingerNames[fingerIndex] << ": ";
        const auto &jointNames = (fingerIndex == 0) ? kThumbJoints : kFingerJoints;

        for (size_t jointIndex = 0; jointIndex < 3; ++jointIndex)
        {
            if (jointIndex > 0)
            {
                out << "   ";
            }
            out << jointNames[jointIndex] << ":";
            if (fingerIndex < angles.size() && jointIndex < angles[fingerIndex].size())
            {
                const Vect3D &e = angles[fingerIndex][jointIndex];
                out << QuantizeTo3Decimals(e.GetX()) << ","
                    << QuantizeTo3Decimals(e.GetY()) << ","
                    << QuantizeTo3Decimals(e.GetZ());
            }
            else
            {
                out << "0.000,0.000,0.000";
            }
        }
    }
    return out.str();
}

int main()
{
    signal(SIGINT, SignalHandler);
    signal(SIGTERM, SignalHandler);

    if (!EnsureSenseCom())
    {
        std::cerr << "Failed to start SenseCom." << std::endl;
        return 1;
    }

    dds_entity_t participant = dds_create_participant(DDS_DOMAIN_DEFAULT, nullptr, nullptr);
    if (participant < 0)
    {
        std::cerr << "dds_create_participant failed: " << dds_strretcode(-participant) << std::endl;
        return 1;
    }

    dds_entity_t right_topic = dds_create_topic(
        participant, &glove_hand_msgs_msg_dds__HandEuler__desc, "rt/glove/right/hand_euler", nullptr, nullptr);
    if (right_topic < 0)
    {
        std::cerr << "dds_create_topic(right) failed: " << dds_strretcode(-right_topic) << std::endl;
        dds_delete(participant);
        return 1;
    }

    dds_entity_t left_topic = dds_create_topic(
        participant, &glove_hand_msgs_msg_dds__HandEuler__desc, "rt/glove/left/hand_euler", nullptr, nullptr);
    if (left_topic < 0)
    {
        std::cerr << "dds_create_topic(left) failed: " << dds_strretcode(-left_topic) << std::endl;
        dds_delete(participant);
        return 1;
    }

    dds_entity_t right_writer = dds_create_writer(participant, right_topic, nullptr, nullptr);
    if (right_writer < 0)
    {
        std::cerr << "dds_create_writer(right) failed: " << dds_strretcode(-right_writer) << std::endl;
        dds_delete(participant);
        return 1;
    }

    dds_entity_t left_writer = dds_create_writer(participant, left_topic, nullptr, nullptr);
    if (left_writer < 0)
    {
        std::cerr << "dds_create_writer(left) failed: " << dds_strretcode(-left_writer) << std::endl;
        dds_delete(participant);
        return 1;
    }

    while (!g_stop.load())
    {
        for (bool rightHand : {true, false})
        {
            if (!HandLayer::DeviceConnected(rightHand))
            {
                continue;
            }

            HandPose pose;
            if (!HandLayer::GetHandPose(rightHand, pose))
            {
                continue;
            }

            std::string compactText = BuildCompactEulerText(pose);
            glove_hand_msgs_msg_dds__HandEuler_ msg{};
            auto eulerText = std::unique_ptr<char, decltype(&dds_free)>(
                dds_string_dup(compactText.c_str()),
                dds_free);
            msg.euler_text = eulerText.get();

            const dds_entity_t writer = rightHand ? right_writer : left_writer;
            dds_return_t rc = dds_write(writer, &msg);
            if (rc != DDS_RETCODE_OK)
            {
                std::cerr << "dds_write failed: " << dds_strretcode(-rc) << std::endl;
            }
            else
            {
                std::cout << (rightHand ? "[Right]" : "[Left]") << '\n'
                          << compactText << "\n"
                          << std::endl;
            }
        }

        std::this_thread::sleep_for(kPublishInterval);
    }

    dds_delete(participant);
    return 0;
}
